version: "3.7"

services:
  server:
    working_dir: /home/node/app
    user: node
    environment:
      - .env
    networks:
      - ajc-web
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app:Z
    image: node:13
  postgres:
    environment:
      - .env
    networks:
      - ajc-web
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    image: postgres:11
  elasticsearch:
    image: 'bitnami/elasticsearch:7'
    ports:
      - '9200:9200'
    networks:
      - ajc-web
    volumes:
      - 'elasticsearch:/bitnami'
  kibana:
    image: 'bitnami/kibana:7'
    environment:
      - .env
    networks:
      - ajc-web
    ports:
      - '5601:5601'
    volumes:
      - 'kibana:/bitnami'
    depends_on:
      - elasticsearch
volumes:
  postgres:
    driver: local
  elasticsearch:
    driver: local
  kibana:
    driver: local
networks:
  ajc-web:
    attachable: true
