version: "3.7"

services:
  client:
    working_dir: /home/node/app
    tty: true
    env_file:
      - .env
    networks:
      - ajc-web
    ports:
      - '8000:8000'
    volumes:
      - ./client:/home/node/app:Z
      - ./shared:/home/node/shared:Z
    image: node:13
  server:
    working_dir: /home/node/app
    tty: true
    env_file:
      - .env
    networks:
      - ajc-web
    ports:
      - '8001:8001'
    volumes:
      - ./server:/home/node/app:Z
      - ./shared:/home/node/shared:Z
    image: node:13
  shared:
    working_dir: /home/node/app
    env_file:
      - .env
    networks:
      - ajc-web
    volumes:
      - ./client:/home/node/app:Z
      - ./shared:/home/node/shared:Z
    image: node:13
  postgres:
    env_file:
      - .env
    networks:
      - ajc-web
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    image: postgres:11
  prometheus:
    env_file:
      - .env
    networks:
      - ajc-web
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    image: prom/prometheus
  grafana:
    env_file:
      - .env
    networks:
      - ajc-web
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
    image: grafana/grafana
volumes:
  postgres:
    driver: local
  grafana:
    driver: local
networks:
  ajc-web:
    attachable: true
