version: "3.7"

services:
  client:
    working_dir: /home/node/app
    tty: true
    env_file:
      - .env
    networks:
      - ajc-web
    ports:
      - '8000:8000'
    volumes:
      - ./client:/home/node/app:Z
      - ./shared:/home/node/shared:Z
    image: node:13
  server:
    working_dir: /home/node/app
    tty: true
    env_file:
      - .env
    networks:
      - ajc-web
    ports:
      - '3000:3000'
    volumes:
      - ./server:/home/node/app:Z
      - ./shared:/home/node/shared:Z
    image: node:13
  shared:
    working_dir: /home/node/app
    env_file:
      - .env
    networks:
      - ajc-web
    volumes:
      - ./client:/home/node/app:Z
      - ./shared:/home/node/shared:Z
    image: node:13
  postgres:
    env_file:
      - .env
    networks:
      - ajc-web
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    image: postgres:11
volumes:
  postgres:
    driver: local
networks:
  ajc-web:
    attachable: true
